<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
	<TargetFramework>net10.0</TargetFramework>
	<Nullable>enable</Nullable>
	<ImplicitUsings>enable</ImplicitUsings>
	<DisableOpenApiGenerator>true</DisableOpenApiGenerator>
    <UserSecretsId>8fd6e2c7-2c8f-4456-9736-ecb43b8c3f17</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
	<PackageReference Include="AutoMapper" Version="16.2.0" />
	<PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.9" />
	<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.9">
	  <PrivateAssets>all</PrivateAssets>
	  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
	</PackageReference>
	<PackageReference Include="Swashbuckle.AspNetCore" Version="10.2.3" />
	<PackageReference Include="Swashbuckle.AspNetCore.Swagger" Version="10.2.3" />
	<PackageReference Include="Swashbuckle.AspNetCore.SwaggerGen" Version="10.2.3" />
	<PackageReference Include="Swashbuckle.AspNetCore.SwaggerUI" Version="10.2.3" />
  </ItemGroup>

  <ItemGroup>
	<ProjectReference Include="..\BankingSystem.Application\BankingSystem.Application.csproj" />
	<ProjectReference Include="..\BankingSystem.Infrastructure\BankingSystem.Infrastructure.csproj" />
  </ItemGroup>

</Project>
